name: Rancher Set Deployment Image Action
description: >
  Set Deployment Image
inputs:
  backend:
    description: 'Server Addr'
    required: true
  token:
    description: 'Bearer Token'
    required: true
  cluster:
    description: 'Cluster Name'
    required: false
  namespace:
    description: 'Namespace'
    required: true
  type:
    description: 'Type of Workload'
    required: false
  workload:
    description: 'Workload Name'
    required: true
  container:
    description: 'Deployment Container Index'
    required: false
  image:
    description: 'Target Image'
    required: true
  wait:
    description: 'Waiting workload available'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'